// packages/astro/src/components/ui/theme-toggle.tsx
import { Moon, Sun } from "lucide-react";
import { Button } from "./button";
import React, { useEffect, useState } from "react";

export default function ThemeToggle() {
  const [theme, setTheme] = useState<"light" | "dark">("light");

  useEffect(() => {
    const isDark = document.documentElement.classList.contains("dark");
    setTheme(isDark ? "dark" : "light");
  }, []);

  const toggleTheme = () => {
    const isDark = document.documentElement.classList.contains("dark");
    const newTheme = isDark ? "light" : "dark";

    document.documentElement.classList.toggle("dark");
    setTheme(newTheme);
  };

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      className="rounded-full cursor-pointer"
    >
      {theme === "light" ? (
        <Moon className="h-5 w-5" />
      ) : (
        <Sun className="h-5 w-5" />
      )}
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}

// packages/astro/src/components/ui/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Sun } from 'lucide-svelte';
  import Button from './Button.svelte';

  const getTheme = () => {
    if (localStorage.getItem("theme")) {
      return localStorage.getItem("theme");
    }
    return 'dark';
  };

  let theme = getTheme();

  const toggleTheme = () => {
    const newTheme = getTheme() == 'dark' ? 'light' : 'dark';
    localStorage.setItem('theme', newTheme);
    if (theme != newTheme) {
      document.documentElement.classList.toggle('dark');
    }
    theme = newTheme;
  };
</script>

<Button variant="ghost" size="icon" onclick={toggleTheme} className="rounded-full cursor-pointer">
  {#if theme === 'light'}
    <Moon class="h-5 w-5" />
  {:else}
    <Sun class="h-5 w-5" />
  {/if}
  <span class="sr-only">Toggle theme</span>
</Button>
