// src/components/motion/MotionWrapper.svelte
<script lang="ts">
import MotionDiv from '@/motion/MotionDiv.svelte';

const defaultAnimations = {
	hidden: {
		opacity: 0,
		y: 20,
	},
	visible: (
		delay = 0,
	) => ({
		opacity: 1,
		y: 0,
		transition: {
			duration: 0.6,
			delay: delay,
			ease: 'easeOut',
		},
	}),
};

let {
	children, delay = 0, ...props
} = $props();
</script>

<MotionDiv
	initial="hidden"
	whileInView="visible"
	viewport={{
		once: true,
		margin: '-100px',
	}}
	variants={defaultAnimations}
	custom={delay}
	{...props}
>
	{@render children?.()}
</MotionDiv>

// packages/astro/src/components/MotionWrapper.tsx
import React from "react";
import { motion } from "framer-motion";
import type { MotionProps } from "framer-motion";

interface MotionWrapperProps extends MotionProps {
  delay?: number;
}

// Default animations for sections
const defaultAnimations = {
  hidden: { opacity: 0, y: 20 },
  visible: (delay: number = 0) => ({
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      delay: delay,
      ease: "easeOut",
    },
  }),
};

export default function MotionWrapper({
  children,
  delay = 0,
  ...props
}: MotionWrapperProps) {
  return (
    <motion.div
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, margin: "-100px" }}
      variants={defaultAnimations}
      custom={delay}
      {...props}
    >
      {children}
    </motion.div>
  );
}
