// packages/astro/src/components/GlassHeader.tsx
import React from 'react';
import ThemeToggle from './ui/theme-toggle';
import { personalInfo } from '@/data';
import { useState } from 'react';
import { Menu, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function GlassHeader() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => setIsMenuOpen(!isMenuOpen);

  return (
    <header className="top-0 sticky z-50 w-full backdrop-blur-md backdrop-filter bg-background/70 dark:bg-background/40 border-b border-border/40 supports-[backdrop-filter]:bg-background/60">
      <div className="container max-w-4xl mx-auto p-4 flex justify-between items-center">
        <motion.a
          className="flex items-center text-lg font-medium"
          href="/"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <img width="50px" src="/images/south-africa.webp" className="inline-block dark:hidden align-middle mr-2.5" />
          <img width="35px" src="/images/luigi-cap.webp" className="dark:inline-block hidden align-middle mr-2.5" />
          {personalInfo.name}
        </motion.a>

        {/* Desktop Navigation */}
        <nav className="hidden md:flex items-center space-x-6 text-sm font-medium">
          {['experience', 'skills', 'projects', 'awards', 'education'].map((item, index) => (
            <motion.a
              key={item}
              href={`#${item}`}
              className="transition-colors hover:text-foreground/80 text-foreground/60"
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.2, delay: index * 0.1 }}
              whileHover={{ y: -2 }}
            >
              {item === 'experience' && '💼 '}
              {item === 'skills' && '🛠️ '}
              {item === 'projects' && '🚀 '}
              {item === 'awards' && '🏆 '}
              {item === 'education' && '🎓 '}
              {item.charAt(0).toUpperCase() + item.slice(1)}
            </motion.a>
          ))}
        </nav>

        <div className="flex items-center space-x-2">
          <ThemeToggle />

          {/* Mobile Menu Button */}
          <motion.button
            className="md:hidden p-2 text-foreground"
            onClick={toggleMenu}
            aria-label="Toggle menu"
            whileTap={{ scale: 0.95 }}
          >
            {isMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </motion.button>
        </div>
      </div>

      {/* Mobile Navigation */}
      <AnimatePresence>
        {isMenuOpen && (
          <motion.div
            className="md:hidden py-4 px-4 border-t border-border/10 backdrop-blur-md backdrop-filter bg-background/80 dark:bg-background/40"
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
          >
            <nav className="flex flex-col space-y-4 text-sm font-medium">
              {['experience', 'skills', 'projects', 'awards', 'education'].map((item, index) => (
                <motion.a
                  key={item}
                  href={`#${item}`}
                  className="transition-colors hover:text-foreground/80 text-foreground/60 py-2"
                  onClick={toggleMenu}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.2, delay: index * 0.1 }}
                >
                  {item === 'experience' && '💼 '}
                  {item === 'skills' && '🛠️ '}
                  {item === 'projects' && '🚀 '}
                  {item === 'awards' && '🏆 '}
                  {item === 'education' && '🎓 '}
                  {item.charAt(0).toUpperCase() + item.slice(1)}
                </motion.a>
              ))}
            </nav>
          </motion.div>
        )}
      </AnimatePresence>
    </header>
  );
}

// src/components/GlassHeader.svelte
<script lang="ts">
	import ThemeToggle from '@/ui/ThemeToggle.svelte';
	import { personalInfo } from '@/data';
	import { Menu, X } from 'lucide-svelte';
	import { AnimatePresence } from 'svelte-motion';
	import MotionA from '@/motion/MotionA.svelte';
	import MotionDiv from '@/motion/MotionDiv.svelte';
	import MotionButton from '@/motion/MotionButton.svelte';
	import southAfrica from '@/images/south-africa.webp';
	import luigiCap from '@/images/luigi-cap.webp';

	let isMenuOpen = $state(false);
	const toggleMenu = () => {
		isMenuOpen = !isMenuOpen;
	};

	const navLinks = [
		{
			name: '💼 Experience',
			href: '#experience',
		},
		{
			name: '🛠️ Skills',
			href: '#skills',
		},
		{
			name: '🚀 Projects',
			href: '#projects',
		},
		{
			name: '🏆 Awards',
			href: '#awards',
		},
		{
			name: '🎓 Education',
			href: '#education',
		},
	];
</script>

<header
	class="bg-background/70 dark:bg-background/40 border-border/40 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 w-full border-b backdrop-blur-md backdrop-filter"
>
	<div class="container mx-auto flex max-w-4xl items-center justify-between p-4">
		<MotionA
			class="flex items-center text-lg font-medium"
			href="/"
			whileHover={{ scale: 1.05 }}
			whileTap={{ scale: 0.95 }}
		>
			<img
				width="50px"
				alt="South Africa"
				src={southAfrica.src}
				class="mr-2.5 inline-block align-middle dark:hidden"
			/>
			<img
				width="35px"
				alt="Luigi Cap"
				src={luigiCap.src}
				class="mr-2.5 hidden align-middle dark:inline-block"
			/>
			{personalInfo.name}
		</MotionA>

		<nav class="hidden items-center space-x-6 text-sm font-medium md:flex">
			{#each navLinks as { name, href }, index (name)}
				<MotionA
					{href}
					class="hover:text-foreground/80 text-foreground/60 transition-colors"
					initial={{ opacity: 0, y: -10 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.2, delay: index * 0.1 }}
					whileHover={{ y: -2 }}
				>
					{name}
				</MotionA>
			{/each}
		</nav>

		<div class="flex items-center space-x-2">
			<ThemeToggle />

			<MotionButton
				class="text-foreground p-2 md:hidden"
				onclick={toggleMenu}
				aria-label="Toggle menu"
				whileTap={{ scale: 0.95 }}
			>
				{#if isMenuOpen}
					<X size={24} />
				{:else}
					<Menu size={24} />
				{/if}
			</MotionButton>
		</div>
	</div>

	<AnimatePresence>
		{#if isMenuOpen}
			<MotionDiv
				class="border-border/10 bg-background/80 dark:bg-background/40 border-t px-4 py-4 backdrop-blur-md backdrop-filter md:hidden"
				initial={{ opacity: 0, height: 0 }}
				animate={{ opacity: 1, height: 'auto' }}
				exit={{ opacity: 0, height: 0 }}
				transition={{ duration: 0.3 }}
			>
				<nav class="flex flex-col space-y-4 text-sm font-medium">
					{#each navLinks as { name, href }, index (name)}
						<MotionA
							{href}
							class="hover:text-foreground/80 text-foreground/60 py-2 transition-colors"
							onclick={toggleMenu}
							initial={{ opacity: 0, x: -20 }}
							animate={{ opacity: 1, x: 0 }}
							transition={{ duration: 0.2, delay: index * 0.1 }}
						>
							{name}
						</MotionA>
					{/each}
				</nav>
			</MotionDiv>
		{/if}
	</AnimatePresence>
</header>
