// packages/astro/src/components/ui/glass-card.tsx
import React, { forwardRef } from "react";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import type { HTMLMotionProps } from "framer-motion";

interface GlassCardProps extends HTMLMotionProps<"div"> {
  hoverEffect?: boolean;
}

const GlassCard = forwardRef<HTMLDivElement, GlassCardProps>(
  ({ className, hoverEffect = true, ...props }, ref) => {
    return (
      <motion.div
        ref={ref}
        className={cn(
          "rounded-lg border border-border/50 bg-background/80 backdrop-blur-md backdrop-filter shadow-sm dark:bg-card/30 dark:backdrop-blur-md",
          hoverEffect &&
            "hover:shadow-md transition-all duration-300 ease-in-out",
          className
        )}
        whileHover={
          hoverEffect
            ? {
                y: -5,
                transition: { duration: 0.2 },
              }
            : undefined
        }
        {...props}
      />
    );
  }
);

GlassCard.displayName = "GlassCard";

export { GlassCard };

// src/components/ui/GlassCard.svelte
<script lang="ts">
import {
	cn, 
} from '@/utils';
import MotionDiv from '@/motion/MotionDiv.svelte';

let {
	children, className, hoverEffect = true, ...props 
} = $props();
</script>

<MotionDiv
	class={cn(
		'border-border/50 bg-background/80 dark:bg-card/30 rounded-lg border shadow-sm backdrop-blur-md backdrop-filter dark:backdrop-blur-md',
		hoverEffect && 'transition-all duration-300 ease-in-out hover:shadow-md',
		className,
	)}
	whileHover={hoverEffect
		? {
			y: -5,
			transition: {
				duration: 0.2, 
			},
		}
		: undefined}
	{...props}
>
	{@render children?.()}
</MotionDiv>
