// packages/astro/src/components/ui/TimelineItem.tsx
import React from 'react';
import { cn } from '@/lib/utils';
import { motion, type MotionProps } from 'framer-motion';

interface TimelineItemProps extends MotionProps {
  title: string;
  titleHref?: string;
  subtitle: string;
  subtitleHref?: string;
  location: string;
  locationHref?: string;
  date: string;
  isLast?: boolean;
  index?: number;
}

export default function TimelineItem({
  title,
  titleHref,
  subtitle,
  subtitleHref,
  location,
  locationHref,
  date,
  isLast = false,
  index = 0,
  children,
}: TimelineItemProps) {
  return (
    <motion.div
      className="relative flex gap-6"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: index * 0.2 }}
      viewport={{ once: true, margin: '-50px' }}
    >
      <div className="flex flex-col items-center">
        <motion.div
          className="flex h-[18px] w-[18px] rounded-full border border-yellow-500/50 bg-background dark:bg-muted z-10"
          initial={{ scale: 0 }}
          whileInView={{ scale: 1 }}
          transition={{
            type: 'spring',
            stiffness: 300,
            damping: 15,
            delay: index * 0.2 + 0.2,
          }}
          viewport={{ once: true, margin: '-50px' }}
        />
        {!isLast && (
          <motion.div
            className="w-px grow bg-gradient-to-b from-yellow-500/50 to-green-500/30 dark:from-yellow-500/30 dark:to-yellow-100/10"
            initial={{ height: 0 }}
            whileInView={{ height: '100%' }}
            transition={{ duration: 0.8, delay: index * 0.2 + 0.3 }}
            viewport={{ once: true, margin: '-50px' }}
          />
        )}
      </div>
      <div className={cn('pb-8', isLast ? 'pb-0' : '')}>
        <motion.div
          className="flex flex-col gap-0.5"
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: index * 0.2 + 0.1 }}
          viewport={{ once: true, margin: '-50px' }}
        >
          <h3 className="font-extrabold mb-2 text-xl">{`📅 ${date}`}</h3>
          <div className="pl-3 mb-6">
            {titleHref != null && titleHref != '' ? (
              <a href={titleHref} target="_blank" rel="noreferrer">
                <h3 className="font-medium">{title}</h3>
              </a>
            ) : (
              <h3 className="font-medium">{title}</h3>
            )}
            {subtitleHref != null && subtitleHref != '' ? (
              <a href={subtitleHref} target="_blank" rel="noreferrer">
                <p className="text-sm text-muted-foreground">{subtitle}</p>
              </a>
            ) : (
              <p className="text-sm text-muted-foreground">{subtitle}</p>
            )}
            {locationHref != null && locationHref != '' ? (
              <a href={locationHref} target="_blank" rel="noreferrer">
                <p className="text-sm text-muted-foreground">📍 {location}</p>
              </a>
            ) : (
              <p className="text-sm text-muted-foreground">📍 {location}</p>
            )}
            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: index * 0.2 + 0.4 }}
              viewport={{ once: true, margin: '-50px' }}
            >
              {children}
            </motion.div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
}

// src/components/ui/TimelineItem.svelte
<script lang="ts">
import {
	cn,
} from '@/utils';
import {
	Motion,
} from 'svelte-motion';

let {
	title,
	titleHref = null,
	subtitle,
	subtitleHref = null,
	location,
	locationHref = null,
	date,
	isLast = false,
	index = 0,
	children,
} = $props();
</script>

<!--
whileInView={{
	opacity: 1,
	y: 0,
}}
viewport={{
	once: true,
	margin: '-50px',
}}
-->
<Motion
	initial={{
		opacity: 0,
		y: 20,
	}}
	transition={{
		duration: 0.3,
		delay: index * 0.1,
	}}
	let:motion
>
	<div class="relative flex gap-6" use:motion>
		<div class="flex flex-col items-center">
			<!--
			whileInView={{
					scale: 1,
			}}
			viewport={{
				once: true,
				margin: '-50px',
			}}
			-->
			<Motion
				initial={{
					scale: 0,
				}}
				transition={{
					type: 'spring',
					stiffness: 300,
					damping: 15,
					delay: index * 0.2 + 0.2,
				}}
			>
				<div class="bg-background dark:bg-muted z-10 flex h-[18px] w-[18px] rounded-full border border-yellow-500/50" use:motion></div>
			</Motion>
			{#if !isLast}
				<!--
				whileInView={{
					height: '100%',
				}}
				viewport={{
					once: true,
					margin: '-50px',
				}}
				-->
				<Motion
					initial={{
						height: 0,
					}}
					transition={{
						duration: 0.8,
						delay: index * 0.2 + 0.3,
					}}
					let:motion
				>
					<div class="w-px grow bg-gradient-to-b from-yellow-500/50 to-green-500/30 dark:from-yellow-500/30 dark:to-yellow-100/10" use:motion></div>
				</Motion>
			{/if}
		</div>
		<div class={cn(
			'pb-8',
			isLast ? 'pb-0' : '',
		)}>
			<!--
			whileInView={{
				opacity: 1,
				x: 0,
		}}
			viewport={{
				once: true,
				margin: '-50px',
			}}
			-->
			<Motion
				initial={{
					opacity: 0,
					x: -20,
				}}
				transition={{
					duration: 0.5,
					delay: index * 0.2 + 0.1,
				}}
			>
				<div class="flex flex-col gap-0.5" use:motion>
					<h3 class="mb-2 text-xl font-extrabold">{`📅 ${date}`}</h3>
					<div class="mb-6 pl-3">
						{#if titleHref}
							<a
								href={titleHref}
								target="_blank"
								rel="noreferrer"
							>
								<h3 class="font-medium">{title}</h3>
							</a>
						{:else}
							<h3 class="font-medium">{title}</h3>
						{/if}
						{#if subtitleHref}
							<a
								href={subtitleHref}
								target="_blank"
								rel="noreferrer"
							>
								<p class="text-muted-foreground text-sm">{subtitle}</p>
							</a>
						{:else}
							<p class="text-muted-foreground text-sm">{subtitle}</p>
						{/if}
						{#if locationHref}
							<a
								href={locationHref}
								target="_blank"
								rel="noreferrer"
							>
								<p class="text-muted-foreground text-sm">📍 {location}</p>
							</a>
						{:else}
							<p class="text-muted-foreground text-sm">📍 {location}</p>
						{/if}
						<div>
							<!--
							whileInView={{
								opacity: 1,
							}}
							viewport={{
								once: true,
								margin: '-50px',
							}}
							-->
							<Motion
								initial={{
									opacity: 0,
								}}
								transition={{
									duration: 0.3,
									delay: index * 0.2 + 0.4,
								}}
								let:motion
							>
								<div use:motion>
									{@render children?.()}
								</div>
							</Motion>
						</div>
					</div>
				</div>
			</Motion>
		</div>
	</div>
</Motion>
